version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
sphinx:
  builder: dirhtml
  configuration: docs/source/conf.py
